//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxOffice
    {
        public int BoxOfficeID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
